### ISSUE TITLE
batch_hmr.pkl is missing

### ISSUE THREAD

**Issue by RusticKey** [zhaofang0627/HPBTT#3]
Hello, I am trying to run your demo code, however it had an issue where a pickle file is missing

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rustickey/projects/HPBTT/demo_fashion.py", line 173, in <module>
    app.run(main)
  File "/home/rustickey/.local/share/virtualenvs/HPBTT-6OKk-9qG/lib/python3.6/site-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/home/rustickey/.local/share/virtualenvs/HPBTT-6OKk-9qG/lib/python3.6/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/home/rustickey/projects/HPBTT/demo_fashion.py", line 158, in main
    batch = pickle.load(open('./HPBTT/batch_hmr.pkl', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: './HPBTT/batch_hmr.pkl'
```

Is there a file that I missed? Thanks.

**Comment by zhaofang0627** [comment]
batch_hmr.pkl is an intermediate output. Please make sure to successfully run the command 'python -m HPBTT.demo_market --name ${NAME} --num_train_epoch ${EPOCH} --img_path ${INPUT}' in run_demo_market.sh.

**Comment by RusticKey** [comment]
I'm sorry for the very late reply. I found out that it was because my TensorFlow installation was not found. However, the problem now is that default_texture.jpg is not found for the HMR reconstruction so I put it off for a while.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rustickey/projects/HPBTT/demo_market.py", line 151, in <module>
    app.run(main)
  File "/home/rustickey/.local/share/virtualenvs/HPBTT-6OKk-9qG/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/rustickey/.local/share/virtualenvs/HPBTT-6OKk-9qG/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/rustickey/projects/HPBTT/demo_market.py", line 139, in main
    predictor = pred_util.MeshPredictor(opts)
  File "/home/rustickey/projects/HPBTT/nnutils/predictor_market.py", line 45, in __init__
    self.m = get_body_mesh('./HPBTT/external/hmr/models/body.obj', trans=np.array([0, 0, 4]), rotation=np.array([np.pi / 2, 0, 0]))
  File "/home/rustickey/projects/HPBTT/experiments/get_body_mesh.py", line 17, in get_body_mesh
    mesh = load_mesh(fname)
  File "/home/rustickey/.local/share/virtualenvs/HPBTT-6OKk-9qG/lib/python3.6/site-packages/opendr/serialization.py", line 26, in load_mesh
    return read_obj(filename)
  File "/home/rustickey/.local/share/virtualenvs/HPBTT-6OKk-9qG/lib/python3.6/site-packages/opendr/serialization.py", line 99, in read_obj
    raise Exception("Unable to find referenced texture map %s" % (src_fname,))
Exception: Unable to find referenced texture map default_texture.jpg
```
